=== szymekplichta/PROJEKTIT/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        
        <xs:element name="dane_osobowe">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="imie" type="xs:string"/>
              <xs:element name="nazwisko" type="xs:string"/>
              <xs:element name="numer_indeksu" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="uczelnia">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nazwa" type="xs:string"/>
              <xs:element name="wydzial" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="oceny">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="przedmiot" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:decimal">
                      <xs:attribute name="nazwa" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== szymekplichta/PROJEKTIT/dane_studenta.xml
<?xml version="1.0" encoding="UTF-8"?>
<student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <dane_osobowe>
        <imie>Szymon</imie>
        <nazwisko>Plichta</nazwisko>
        <numer_indeksu>208960</numer_indeksu>
    </dane_osobowe>
    <uczelnia>
        <nazwa>Politechnika Gda≈Ñska</nazwa>
        <wydzial>ETI</wydzial>
    </uczelnia>
    <oceny>
        <przedmiot nazwa="NITIJP">5.0</przedmiot>
        <przedmiot nazwa="Projekt">4.5</przedmiot>
    </oceny>
</student>
